// GENERATED FILE — do not edit by hand.
// Run `node scripts/build-fonts.mjs` to regenerate.
//
// Every family bundled in src/fonts-library.css, which is every family the
// font pickers in Settings → Appearance are allowed to offer. All of them are
// SIL Open Font License or Apache 2.0 — that is the condition for being on
// this list, and it's what makes shipping them legal.

/** Which slot a family is shaped for. Groups the pickers, nothing more. */
export type FontCategory = "serif" | "sans" | "display" | "hand" | "mono";

export type LibraryFont = {
  family: string;
  cat: FontCategory;
  /** Whether a real italic was bundled, rather than the browser slanting it. */
  italic: boolean;
};

export const FONT_LIBRARY: readonly LibraryFont[] = [
  { family: "EB Garamond", cat: "serif", italic: true },
  { family: "Cormorant Garamond", cat: "serif", italic: true },
  { family: "Lora", cat: "serif", italic: true },
  { family: "Crimson Pro", cat: "serif", italic: true },
  { family: "Crimson Text", cat: "serif", italic: true },
  { family: "Spectral", cat: "serif", italic: true },
  { family: "Libre Baskerville", cat: "serif", italic: true },
  { family: "Vollkorn", cat: "serif", italic: true },
  { family: "Alegreya", cat: "serif", italic: true },
  { family: "Literata", cat: "serif", italic: true },
  { family: "Petrona", cat: "serif", italic: true },
  { family: "Faustina", cat: "serif", italic: true },
  { family: "Bitter", cat: "serif", italic: true },
  { family: "Zilla Slab", cat: "serif", italic: true },
  { family: "Source Serif 4", cat: "serif", italic: true },
  { family: "Cardo", cat: "serif", italic: true },
  { family: "Gentium Book Plus", cat: "serif", italic: true },
  { family: "Frank Ruhl Libre", cat: "serif", italic: false },
  { family: "Merriweather", cat: "serif", italic: true },
  { family: "PT Serif", cat: "serif", italic: true },
  { family: "Domine", cat: "serif", italic: false },
  { family: "Eczar", cat: "serif", italic: false },
  { family: "Rosarivo", cat: "serif", italic: true },
  { family: "Neuton", cat: "serif", italic: true },
  { family: "Noto Serif", cat: "serif", italic: true },
  { family: "Andada Pro", cat: "serif", italic: true },
  { family: "Manrope", cat: "sans", italic: false },
  { family: "DM Sans", cat: "sans", italic: false },
  { family: "Plus Jakarta Sans", cat: "sans", italic: false },
  { family: "Figtree", cat: "sans", italic: false },
  { family: "Lexend", cat: "sans", italic: false },
  { family: "Outfit", cat: "sans", italic: false },
  { family: "Sora", cat: "sans", italic: false },
  { family: "Space Grotesk", cat: "sans", italic: false },
  { family: "Work Sans", cat: "sans", italic: false },
  { family: "Public Sans", cat: "sans", italic: false },
  { family: "Karla", cat: "sans", italic: false },
  { family: "Rubik", cat: "sans", italic: false },
  { family: "Nunito Sans", cat: "sans", italic: false },
  { family: "Nunito", cat: "sans", italic: false },
  { family: "Mulish", cat: "sans", italic: false },
  { family: "Cabin", cat: "sans", italic: false },
  { family: "Barlow", cat: "sans", italic: false },
  { family: "Archivo", cat: "sans", italic: false },
  { family: "Urbanist", cat: "sans", italic: false },
  { family: "Epilogue", cat: "sans", italic: false },
  { family: "Chivo", cat: "sans", italic: false },
  { family: "Raleway", cat: "sans", italic: false },
  { family: "Quicksand", cat: "sans", italic: false },
  { family: "Josefin Sans", cat: "sans", italic: false },
  { family: "Source Sans 3", cat: "sans", italic: false },
  { family: "Assistant", cat: "sans", italic: false },
  { family: "Hanken Grotesk", cat: "sans", italic: false },
  { family: "Comfortaa", cat: "sans", italic: false },
  { family: "Fredoka", cat: "sans", italic: false },
  { family: "Fira Sans", cat: "sans", italic: false },
  { family: "PT Sans", cat: "sans", italic: false },
  { family: "Signika", cat: "sans", italic: false },
  { family: "Atkinson Hyperlegible", cat: "sans", italic: false },
  { family: "Lato", cat: "sans", italic: false },
  { family: "Open Sans", cat: "sans", italic: false },
  { family: "Playfair Display", cat: "display", italic: false },
  { family: "Cinzel", cat: "display", italic: false },
  { family: "Cinzel Decorative", cat: "display", italic: false },
  { family: "Marcellus", cat: "display", italic: false },
  { family: "Gilda Display", cat: "display", italic: false },
  { family: "Prata", cat: "display", italic: false },
  { family: "Yeseva One", cat: "display", italic: false },
  { family: "Old Standard TT", cat: "display", italic: false },
  { family: "Italiana", cat: "display", italic: false },
  { family: "Julius Sans One", cat: "display", italic: false },
  { family: "Cormorant Unicase", cat: "display", italic: false },
  { family: "Cormorant SC", cat: "display", italic: false },
  { family: "IM Fell English", cat: "display", italic: false },
  { family: "Uncial Antiqua", cat: "display", italic: false },
  { family: "MedievalSharp", cat: "display", italic: false },
  { family: "Grenze Gotisch", cat: "display", italic: false },
  { family: "Metamorphous", cat: "display", italic: false },
  { family: "Almendra", cat: "display", italic: false },
  { family: "Pirata One", cat: "display", italic: false },
  { family: "Trade Winds", cat: "display", italic: false },
  { family: "Bodoni Moda", cat: "display", italic: false },
  { family: "DM Serif Display", cat: "display", italic: false },
  { family: "Abril Fatface", cat: "display", italic: false },
  { family: "Bebas Neue", cat: "display", italic: false },
  { family: "Oswald", cat: "display", italic: false },
  { family: "Philosopher", cat: "display", italic: false },
  { family: "Amatic SC", cat: "display", italic: false },
  { family: "Cormorant Infant", cat: "display", italic: false },
  { family: "Antic Didone", cat: "display", italic: false },
  { family: "Righteous", cat: "display", italic: false },
  { family: "Marcellus SC", cat: "display", italic: false },
  { family: "Alegreya SC", cat: "display", italic: false },
  { family: "Caveat", cat: "hand", italic: false },
  { family: "Kalam", cat: "hand", italic: false },
  { family: "Shadows Into Light", cat: "hand", italic: false },
  { family: "Indie Flower", cat: "hand", italic: false },
  { family: "Architects Daughter", cat: "hand", italic: false },
  { family: "Patrick Hand", cat: "hand", italic: false },
  { family: "Gloria Hallelujah", cat: "hand", italic: false },
  { family: "Tangerine", cat: "hand", italic: false },
  { family: "Great Vibes", cat: "hand", italic: false },
  { family: "Dancing Script", cat: "hand", italic: false },
  { family: "Handlee", cat: "hand", italic: false },
  { family: "Delius", cat: "hand", italic: false },
  { family: "Neucha", cat: "hand", italic: false },
  { family: "JetBrains Mono", cat: "mono", italic: false },
  { family: "IBM Plex Mono", cat: "mono", italic: false },
  { family: "Fira Code", cat: "mono", italic: false },
  { family: "Source Code Pro", cat: "mono", italic: false },
  { family: "Space Mono", cat: "mono", italic: false },
  { family: "Roboto Mono", cat: "mono", italic: false },
  { family: "Inconsolata", cat: "mono", italic: false },
  { family: "DM Mono", cat: "mono", italic: false },
  { family: "Courier Prime", cat: "mono", italic: false },
  { family: "Azeret Mono", cat: "mono", italic: false },
  { family: "Noto Sans Mono", cat: "mono", italic: false },
  { family: "Anonymous Pro", cat: "mono", italic: false },
  { family: "Cousine", cat: "mono", italic: false },
];
